name = "LogClustering"
uuid = "e9035d2f-2000-5483-2fb3-67d8e80efaf9"
author = ["Sebastian Wiesendahl <sebastian@wiesendahl.de>", "Sebastian Wiesendahl <sebastian.wiesendahl@dlr.de>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
